//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.10 at 05:55:13 PM CET 
//


package rs.tim14.xml.model.korisnici;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rs.tim14.xml.korisnici package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Adresa_QNAME = new QName("http://www.xml.tim14.rs/korisnici", "adresa");
    private final static QName _TLiceBrojFaksa_QNAME = new QName("http://www.xml.tim14.rs/korisnici", "broj_faksa");
    private final static QName _TLiceEmail_QNAME = new QName("http://www.xml.tim14.rs/korisnici", "email");
    private final static QName _TLiceBrojMobilnogTelefona_QNAME = new QName("http://www.xml.tim14.rs/korisnici", "broj_mobilnog_telefona");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rs.tim14.xml.korisnici
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PunoIme }
     * 
     */
    public PunoIme createPunoIme() {
        return new PunoIme();
    }

    /**
     * Create an instance of {@link Drzavljanstvo }
     * 
     */
    public Drzavljanstvo createDrzavljanstvo() {
        return new Drzavljanstvo();
    }

    /**
     * Create an instance of {@link Adresa }
     * 
     */
    public Adresa createAdresa() {
        return new Adresa();
    }

    /**
     * Create an instance of {@link TFizickoLice }
     * 
     */
    public TFizickoLice createTFizickoLice() {
        return new TFizickoLice();
    }

    /**
     * Create an instance of {@link TPravnoLice }
     * 
     */
    public TPravnoLice createTPravnoLice() {
        return new TPravnoLice();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Adresa }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.xml.tim14.rs/korisnici", name = "adresa")
    public JAXBElement<Adresa> createAdresa(Adresa value) {
        return new JAXBElement<Adresa>(_Adresa_QNAME, Adresa.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.xml.tim14.rs/korisnici", name = "broj_faksa", scope = TLice.class)
    public JAXBElement<String> createTLiceBrojFaksa(String value) {
        return new JAXBElement<String>(_TLiceBrojFaksa_QNAME, String.class, TLice.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.xml.tim14.rs/korisnici", name = "email", scope = TLice.class)
    public JAXBElement<String> createTLiceEmail(String value) {
        return new JAXBElement<String>(_TLiceEmail_QNAME, String.class, TLice.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.xml.tim14.rs/korisnici", name = "broj_mobilnog_telefona", scope = TLice.class)
    public JAXBElement<String> createTLiceBrojMobilnogTelefona(String value) {
        return new JAXBElement<String>(_TLiceBrojMobilnogTelefona_QNAME, String.class, TLice.class, value);
    }
}
