//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.28 at 10:50:44 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.xml.tim14.rs/user", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package rs.tim14.xml.model;
