//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.10 at 05:55:12 PM CET 
//


package rs.tim14.xml.model.autorska_prava;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TVrsta_autorskog_dela.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TVrsta_autorskog_dela">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="knjizevno_delo"/>
 *     &lt;enumeration value="racunarski_program"/>
 *     &lt;enumeration value="muzicko_delo"/>
 *     &lt;enumeration value="dramsko_delo"/>
 *     &lt;enumeration value="filmsko_delo"/>
 *     &lt;enumeration value="likovno_delo"/>
 *     &lt;enumeration value="primenjeno_delo"/>
 *     &lt;enumeration value="patenti"/>
 *     &lt;enumeration value="naucna_teorija"/>
 *     &lt;enumeration value="naucna_delatnost"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TVrsta_autorskog_dela")
@XmlEnum
public enum TVrstaAutorskogDela {

    @XmlEnumValue("књижевно дело")
    KNJIZEVNO_DELO("књижевно дело"),
    @XmlEnumValue("рачунарски програм")
    RACUNARSKI_PROGRAM("рачунарски програм"),
    @XmlEnumValue("музичко дело")
    MUZICKO_DELO("музичко дело"),
    @XmlEnumValue("драмско дело")
    DRAMSKO_DELO("драмско дело"),
    @XmlEnumValue("филмско дело")
    FILMSKO_DELO("филмско дело"),
    @XmlEnumValue("ликовно дело")
    LIKOVNO_DELO("ликовно дело"),
    @XmlEnumValue("примењено дело")
    PRIMENJENO_DELO("примењено дело"),
    @XmlEnumValue("патенти")
    PATENTI("патенти"),
    @XmlEnumValue("научна теорија")
    NAUCNA_TEORIJA("научна теорија"),
    @XmlEnumValue("научна делатност")
    NAUCNA_DELATNOST("научна делатност");
    private final String value;

    TVrstaAutorskogDela(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TVrstaAutorskogDela fromValue(String v) {
        for (TVrstaAutorskogDela c: TVrstaAutorskogDela.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
