//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.10 at 05:55:13 PM CET 
//


package rs.tim14.xml.model.autorska_prava;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;
import java.math.BigInteger;
import java.util.Date;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TPrijava", propOrder = {
    "brojPrijave",
    "datumPodnosenja"
})
public class TPrijava {

    @XmlElement(name = "broj_prijave", required = true)
    protected BrojPrijave brojPrijave;
    @XmlElement(name = "datum_podnosenja", required = true)
    protected DatumPodnosenja datumPodnosenja;

    public BrojPrijave getBrojPrijave() {
        return brojPrijave;
    }

    public void setBrojPrijave(BrojPrijave value) {
        this.brojPrijave = value;
    }

    public DatumPodnosenja getDatumPodnosenja() {
        return datumPodnosenja;
    }

    public void setDatumPodnosenja(DatumPodnosenja value) {
        this.datumPodnosenja = value;
    }



    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "value"
    })
    public static class BrojPrijave {

        @XmlValue
        @XmlSchemaType(name = "positiveInteger")
        protected BigInteger value;
        @XmlAttribute(name = "property")
        @XmlSchemaType(name = "anySimpleType")
        protected String property;
        @XmlAttribute(name = "datatype")
        @XmlSchemaType(name = "anySimpleType")
        protected String datatype;
        public BigInteger getValue() {
            return value;
        }

        public void setValue(BigInteger value) {
            this.value = value;
        }
        public String getProperty() {
            return property;
        }

        public void setProperty(String value) {
            this.property = value;
        }
        public String getDatatype() {
            return datatype;
        }

        public void setDatatype(String value) {
            this.datatype = value;
        }

    }

    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "value"
    })
    public static class DatumPodnosenja {

        @XmlValue
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar value;
        @XmlAttribute(name = "property")
        @XmlSchemaType(name = "anySimpleType")
        protected String property;
        @XmlAttribute(name = "datatype")
        @XmlSchemaType(name = "anySimpleType")
        protected String datatype;

        public XMLGregorianCalendar getValue() {
            return value;
        }

        public void setValue(XMLGregorianCalendar value) {
            this.value = value;
        }
        public String getProperty() {
            return property;
        }
        public void setProperty(String value) {
            this.property = value;
        }
        public String getDatatype() {
            return datatype;
        }

        public void setDatatype(String value) {
            this.datatype = value;
        }

    }

    @Override
    public String toString() {
        final StringBuffer sb = new StringBuffer("{");
        sb.append("broj prijave: ").append(brojPrijave);
        if (datumPodnosenja != null) sb.append(", datum podnosenja: ").append(datumPodnosenja);
        sb.append('}');
        return sb.toString();
    }
}
