//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.10 at 05:55:12 PM CET 
//


package rs.tim14.xml.model.autorska_prava;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import rs.tim14.xml.model.korisnici.Adresa;
import rs.tim14.xml.model.korisnici.PunoIme;
import rs.tim14.xml.model.korisnici.TLice;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="podnosilac" type="{http://www.xml.tim14.rs/korisnici}TLice"/>
 *         &lt;element name="punomocnik" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://www.xml.tim14.rs/korisnici}puno_ime"/>
 *                   &lt;element ref="{http://www.xml.tim14.rs/korisnici}adresa"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="autorsko_delo">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="naslov_autorskog_dela" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="vrsta_autorskog_dela" type="{http://www.xml.tim14.rs/autorska_prava}TVrsta_autorskog_dela"/>
 *                   &lt;element name="forma_zapisa" type="{http://www.xml.tim14.rs/autorska_prava}TForma_zapisa"/>
 *                   &lt;element name="podaci_o_autoru">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="autor" type="{http://www.xml.tim14.rs/autorska_prava}TAutor" maxOccurs="unbounded" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="izvorno_autorsko_delo" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="naslov_izvornog_autorskog_dela">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;minLength value="1"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="autor_izvornog_autorskog_dela" type="{http://www.xml.tim14.rs/autorska_prava}TAutor"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="stvoreno_u_radnom_odnosu" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                   &lt;element name="nacin_koriscenja_autorskog_dela" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="primer_autorskog_dela">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="putanja_do_primera" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="tip_primera" type="{http://www.xml.tim14.rs/autorska_prava}TTip_primera"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="opis_autorskog_dela" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="putanja_do_opisa" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="datum_podnosenja" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       &lt;attribute name="broj_prijave" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "podnosilac",
    "punomocnik",
    "autorskoDelo"
})
@XmlRootElement(name = "zahtev_za_autorska_prava")
public class ZahtevZaAutorskaPrava {

    @XmlElement(required = true)
    protected TLice podnosilac;
    @XmlElementRef(name = "punomocnik", namespace = "http://www.xml.tim14.rs/autorska_prava", type = JAXBElement.class, required = false)
    protected JAXBElement<Punomocnik> punomocnik;
    @XmlElement(name = "autorsko_delo", required = true)
    protected AutorskoDelo autorskoDelo;
    @XmlAttribute(name = "datum_podnosenja")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datumPodnosenja;
    @XmlAttribute(name = "broj_prijave")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger brojPrijave;

    /**
     * Gets the value of the podnosilac property.
     * 
     * @return
     *     possible object is
     *     {@link TLice }
     *     
     */
    public TLice getPodnosilac() {
        return podnosilac;
    }

    /**
     * Sets the value of the podnosilac property.
     * 
     * @param value
     *     allowed object is
     *     {@link TLice }
     *     
     */
    public void setPodnosilac(TLice value) {
        this.podnosilac = value;
    }

    /**
     * Gets the value of the punomocnik property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Punomocnik }{@code >}
     *     
     */
    public JAXBElement<Punomocnik> getPunomocnik() {
        return punomocnik;
    }

    /**
     * Sets the value of the punomocnik property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Punomocnik }{@code >}
     *     
     */
    public void setPunomocnik(JAXBElement<Punomocnik> value) {
        this.punomocnik = value;
    }

    /**
     * Gets the value of the autorskoDelo property.
     * 
     * @return
     *     possible object is
     *     {@link AutorskoDelo }
     *     
     */
    public AutorskoDelo getAutorskoDelo() {
        return autorskoDelo;
    }

    /**
     * Sets the value of the autorskoDelo property.
     * 
     * @param value
     *     allowed object is
     *     {@link AutorskoDelo }
     *     
     */
    public void setAutorskoDelo(AutorskoDelo value) {
        this.autorskoDelo = value;
    }

    /**
     * Gets the value of the datumPodnosenja property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumPodnosenja() {
        return datumPodnosenja;
    }

    /**
     * Sets the value of the datumPodnosenja property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumPodnosenja(XMLGregorianCalendar value) {
        this.datumPodnosenja = value;
    }

    /**
     * Gets the value of the brojPrijave property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getBrojPrijave() {
        return brojPrijave;
    }

    /**
     * Sets the value of the brojPrijave property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setBrojPrijave(BigInteger value) {
        this.brojPrijave = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="naslov_autorskog_dela" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="vrsta_autorskog_dela" type="{http://www.xml.tim14.rs/autorska_prava}TVrsta_autorskog_dela"/>
     *         &lt;element name="forma_zapisa" type="{http://www.xml.tim14.rs/autorska_prava}TForma_zapisa"/>
     *         &lt;element name="podaci_o_autoru">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="autor" type="{http://www.xml.tim14.rs/autorska_prava}TAutor" maxOccurs="unbounded" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="izvorno_autorsko_delo" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="naslov_izvornog_autorskog_dela">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;minLength value="1"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="autor_izvornog_autorskog_dela" type="{http://www.xml.tim14.rs/autorska_prava}TAutor"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="stvoreno_u_radnom_odnosu" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *         &lt;element name="nacin_koriscenja_autorskog_dela" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="primer_autorskog_dela">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="putanja_do_primera" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="tip_primera" type="{http://www.xml.tim14.rs/autorska_prava}TTip_primera"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="opis_autorskog_dela" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="putanja_do_opisa" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "naslovAutorskogDela",
        "vrstaAutorskogDela",
        "formaZapisa",
        "podaciOAutoru",
        "izvornoAutorskoDelo",
        "stvorenoURadnomOdnosu",
        "nacinKoriscenjaAutorskogDela",
        "primerAutorskogDela",
        "opisAutorskogDela"
    })
    public static class AutorskoDelo {

        @XmlElement(name = "naslov_autorskog_dela", required = true)
        protected String naslovAutorskogDela;
        @XmlElement(name = "vrsta_autorskog_dela", required = true)
        protected TVrstaAutorskogDela vrstaAutorskogDela;
        @XmlElement(name = "forma_zapisa", required = true)
        protected TFormaZapisa formaZapisa;
        @XmlElement(name = "podaci_o_autoru", required = true)
        protected PodaciOAutoru podaciOAutoru;
        @XmlElement(name = "izvorno_autorsko_delo")
        protected IzvornoAutorskoDelo izvornoAutorskoDelo;
        @XmlElement(name = "stvoreno_u_radnom_odnosu")
        protected boolean stvorenoURadnomOdnosu;
        @XmlElement(name = "nacin_koriscenja_autorskog_dela")
        protected String nacinKoriscenjaAutorskogDela;
        @XmlElement(name = "primer_autorskog_dela", required = true)
        protected PrimerAutorskogDela primerAutorskogDela;
        @XmlElement(name = "opis_autorskog_dela")
        protected OpisAutorskogDela opisAutorskogDela;

        /**
         * Gets the value of the naslovAutorskogDela property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNaslovAutorskogDela() {
            return naslovAutorskogDela;
        }

        /**
         * Sets the value of the naslovAutorskogDela property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNaslovAutorskogDela(String value) {
            this.naslovAutorskogDela = value;
        }

        /**
         * Gets the value of the vrstaAutorskogDela property.
         * 
         * @return
         *     possible object is
         *     {@link TVrstaAutorskogDela }
         *     
         */
        public TVrstaAutorskogDela getVrstaAutorskogDela() {
            return vrstaAutorskogDela;
        }

        /**
         * Sets the value of the vrstaAutorskogDela property.
         * 
         * @param value
         *     allowed object is
         *     {@link TVrstaAutorskogDela }
         *     
         */
        public void setVrstaAutorskogDela(TVrstaAutorskogDela value) {
            this.vrstaAutorskogDela = value;
        }

        /**
         * Gets the value of the formaZapisa property.
         * 
         * @return
         *     possible object is
         *     {@link TFormaZapisa }
         *     
         */
        public TFormaZapisa getFormaZapisa() {
            return formaZapisa;
        }

        /**
         * Sets the value of the formaZapisa property.
         * 
         * @param value
         *     allowed object is
         *     {@link TFormaZapisa }
         *     
         */
        public void setFormaZapisa(TFormaZapisa value) {
            this.formaZapisa = value;
        }

        /**
         * Gets the value of the podaciOAutoru property.
         * 
         * @return
         *     possible object is
         *     {@link PodaciOAutoru }
         *     
         */
        public PodaciOAutoru getPodaciOAutoru() {
            return podaciOAutoru;
        }

        /**
         * Sets the value of the podaciOAutoru property.
         * 
         * @param value
         *     allowed object is
         *     {@link PodaciOAutoru }
         *     
         */
        public void setPodaciOAutoru(PodaciOAutoru value) {
            this.podaciOAutoru = value;
        }

        /**
         * Gets the value of the izvornoAutorskoDelo property.
         * 
         * @return
         *     possible object is
         *     {@link IzvornoAutorskoDelo }
         *     
         */
        public IzvornoAutorskoDelo getIzvornoAutorskoDelo() {
            return izvornoAutorskoDelo;
        }

        /**
         * Sets the value of the izvornoAutorskoDelo property.
         * 
         * @param value
         *     allowed object is
         *     {@link IzvornoAutorskoDelo }
         *     
         */
        public void setIzvornoAutorskoDelo(IzvornoAutorskoDelo value) {
            this.izvornoAutorskoDelo = value;
        }

        /**
         * Gets the value of the stvorenoURadnomOdnosu property.
         * 
         */
        public boolean isStvorenoURadnomOdnosu() {
            return stvorenoURadnomOdnosu;
        }

        /**
         * Sets the value of the stvorenoURadnomOdnosu property.
         * 
         */
        public void setStvorenoURadnomOdnosu(boolean value) {
            this.stvorenoURadnomOdnosu = value;
        }

        /**
         * Gets the value of the nacinKoriscenjaAutorskogDela property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNacinKoriscenjaAutorskogDela() {
            return nacinKoriscenjaAutorskogDela;
        }

        /**
         * Sets the value of the nacinKoriscenjaAutorskogDela property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNacinKoriscenjaAutorskogDela(String value) {
            this.nacinKoriscenjaAutorskogDela = value;
        }

        /**
         * Gets the value of the primerAutorskogDela property.
         * 
         * @return
         *     possible object is
         *     {@link PrimerAutorskogDela }
         *     
         */
        public PrimerAutorskogDela getPrimerAutorskogDela() {
            return primerAutorskogDela;
        }

        /**
         * Sets the value of the primerAutorskogDela property.
         * 
         * @param value
         *     allowed object is
         *     {@link PrimerAutorskogDela }
         *     
         */
        public void setPrimerAutorskogDela(PrimerAutorskogDela value) {
            this.primerAutorskogDela = value;
        }

        /**
         * Gets the value of the opisAutorskogDela property.
         * 
         * @return
         *     possible object is
         *     {@link OpisAutorskogDela }
         *     
         */
        public OpisAutorskogDela getOpisAutorskogDela() {
            return opisAutorskogDela;
        }

        /**
         * Sets the value of the opisAutorskogDela property.
         * 
         * @param value
         *     allowed object is
         *     {@link OpisAutorskogDela }
         *     
         */
        public void setOpisAutorskogDela(OpisAutorskogDela value) {
            this.opisAutorskogDela = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="naslov_izvornog_autorskog_dela">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;minLength value="1"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="autor_izvornog_autorskog_dela" type="{http://www.xml.tim14.rs/autorska_prava}TAutor"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "naslovIzvornogAutorskogDela",
            "autorIzvornogAutorskogDela"
        })
        public static class IzvornoAutorskoDelo {

            @XmlElement(name = "naslov_izvornog_autorskog_dela", required = true)
            protected String naslovIzvornogAutorskogDela;
            @XmlElement(name = "autor_izvornog_autorskog_dela", required = true)
            protected TAutor autorIzvornogAutorskogDela;

            /**
             * Gets the value of the naslovIzvornogAutorskogDela property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNaslovIzvornogAutorskogDela() {
                return naslovIzvornogAutorskogDela;
            }

            /**
             * Sets the value of the naslovIzvornogAutorskogDela property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNaslovIzvornogAutorskogDela(String value) {
                this.naslovIzvornogAutorskogDela = value;
            }

            /**
             * Gets the value of the autorIzvornogAutorskogDela property.
             * 
             * @return
             *     possible object is
             *     {@link TAutor }
             *     
             */
            public TAutor getAutorIzvornogAutorskogDela() {
                return autorIzvornogAutorskogDela;
            }

            /**
             * Sets the value of the autorIzvornogAutorskogDela property.
             * 
             * @param value
             *     allowed object is
             *     {@link TAutor }
             *     
             */
            public void setAutorIzvornogAutorskogDela(TAutor value) {
                this.autorIzvornogAutorskogDela = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="putanja_do_opisa" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "putanjaDoOpisa"
        })
        public static class OpisAutorskogDela {

            @XmlElement(name = "putanja_do_opisa", required = true)
            protected String putanjaDoOpisa;

            /**
             * Gets the value of the putanjaDoOpisa property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPutanjaDoOpisa() {
                return putanjaDoOpisa;
            }

            /**
             * Sets the value of the putanjaDoOpisa property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPutanjaDoOpisa(String value) {
                this.putanjaDoOpisa = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="autor" type="{http://www.xml.tim14.rs/autorska_prava}TAutor" maxOccurs="unbounded" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "autor"
        })
        public static class PodaciOAutoru {

            @XmlElement(nillable = true)
            protected List<TAutor> autor;

            /**
             * Gets the value of the autor property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the autor property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getAutor().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link TAutor }
             * 
             * 
             */
            public List<TAutor> getAutor() {
                if (autor == null) {
                    autor = new ArrayList<TAutor>();
                }
                return this.autor;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="putanja_do_primera" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="tip_primera" type="{http://www.xml.tim14.rs/autorska_prava}TTip_primera"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "putanjaDoPrimera",
            "tipPrimera"
        })
        public static class PrimerAutorskogDela {

            @XmlElement(name = "putanja_do_primera", required = true)
            protected String putanjaDoPrimera;
            @XmlElement(name = "tip_primera", required = true)
            protected TTipPrimera tipPrimera;

            /**
             * Gets the value of the putanjaDoPrimera property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPutanjaDoPrimera() {
                return putanjaDoPrimera;
            }

            /**
             * Sets the value of the putanjaDoPrimera property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPutanjaDoPrimera(String value) {
                this.putanjaDoPrimera = value;
            }

            /**
             * Gets the value of the tipPrimera property.
             * 
             * @return
             *     possible object is
             *     {@link TTipPrimera }
             *     
             */
            public TTipPrimera getTipPrimera() {
                return tipPrimera;
            }

            /**
             * Sets the value of the tipPrimera property.
             * 
             * @param value
             *     allowed object is
             *     {@link TTipPrimera }
             *     
             */
            public void setTipPrimera(TTipPrimera value) {
                this.tipPrimera = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.xml.tim14.rs/korisnici}puno_ime"/>
     *         &lt;element ref="{http://www.xml.tim14.rs/korisnici}adresa"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "punoIme",
        "adresa"
    })
    public static class Punomocnik {

        @XmlElement(name = "puno_ime", namespace = "http://www.xml.tim14.rs/korisnici", required = true)
        protected PunoIme punoIme;
        @XmlElement(namespace = "http://www.xml.tim14.rs/korisnici", required = true, nillable = true)
        protected Adresa adresa;

        /**
         * Gets the value of the punoIme property.
         * 
         * @return
         *     possible object is
         *     {@link PunoIme }
         *     
         */
        public PunoIme getPunoIme() {
            return punoIme;
        }

        /**
         * Sets the value of the punoIme property.
         * 
         * @param value
         *     allowed object is
         *     {@link PunoIme }
         *     
         */
        public void setPunoIme(PunoIme value) {
            this.punoIme = value;
        }

        /**
         * Gets the value of the adresa property.
         * 
         * @return
         *     possible object is
         *     {@link Adresa }
         *     
         */
        public Adresa getAdresa() {
            return adresa;
        }

        /**
         * Sets the value of the adresa property.
         * 
         * @param value
         *     allowed object is
         *     {@link Adresa }
         *     
         */
        public void setAdresa(Adresa value) {
            this.adresa = value;
        }

    }

}
