//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.10 at 05:55:12 PM CET 
//


package rs.tim14.xml.model.autorska_prava;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import rs.tim14.xml.model.korisnici.Adresa;
import rs.tim14.xml.model.korisnici.PunoIme;
import rs.tim14.xml.model.korisnici.TLice;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "podnosilac",
    "punomocnik",
    "autorskoDelo"
})
@XmlRootElement(name = "zahtev_za_autorska_prava")
public class ZahtevZaAutorskaPrava {

    @XmlElement(required = true)
    protected TLice podnosilac;

    @XmlElement(name = "punomocnik", required = false)
    protected Punomocnik punomocnik;
    @XmlElement(name = "autorsko_delo", required = true)
    protected AutorskoDelo autorskoDelo;
    @XmlAttribute(name = "datum_podnosenja")
    @XmlSchemaType(name = "date")
    protected Date datumPodnosenja;
    @XmlAttribute(name = "broj_prijave")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger brojPrijave;

    public TLice getPodnosilac() {
        return podnosilac;
    }

    public void setPodnosilac(TLice value) {
        this.podnosilac = value;
    }

    public Punomocnik getPunomocnik() {
        return punomocnik;
    }

    public void setPunomocnik(Punomocnik value) {
        this.punomocnik = value;
    }

    public AutorskoDelo getAutorskoDelo() {
        return autorskoDelo;
    }

    public void setAutorskoDelo(AutorskoDelo value) {
        this.autorskoDelo = value;
    }

    public Date getDatumPodnosenja() {
        return datumPodnosenja;
    }

    public void setDatumPodnosenja(Date value) {
        this.datumPodnosenja = value;
    }

    public BigInteger getBrojPrijave() {
        return brojPrijave;
    }

    public void setBrojPrijave(BigInteger value) {
        this.brojPrijave = value;
    }

    @Override
    public String toString() {
        final StringBuffer sb = new StringBuffer();
        sb.append("Zahtev za autorska prava:");
        sb.append("\n\tDatum podnosenja: ").append(datumPodnosenja);
        sb.append("\n\tBroj prijave: ").append(brojPrijave);
        sb.append("\n\tPodnosilac:").append(podnosilac.toString("\t\t"));
        sb.append("\n\tPunomocnik: ").append(punomocnik);
        sb.append("\n\tAutorsko delo: ").append(autorskoDelo);
        return sb.toString();
    }
}
