//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.10 at 05:55:13 PM CET 
//


package rs.tim14.xml.model.korisnici;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "tipDrzavljanstva",
    "jmbg",
    "brojPasosa"
})
@XmlRootElement(name = "drzavljanstvo")
public class Drzavljanstvo {

    @XmlElement(name = "tip_drzavljanstva", required = true)
    protected TTipDrzavljanstva tipDrzavljanstva;
    @XmlElement(required = true)
    protected String jmbg;
    @XmlElement(name = "broj_pasosa", required = true)
    protected String brojPasosa;
    public TTipDrzavljanstva getTipDrzavljanstva() {
        return tipDrzavljanstva;
    }
    public void setTipDrzavljanstva(TTipDrzavljanstva value) {
        this.tipDrzavljanstva = value;
    }
    public String getJmbg() {
        return jmbg;
    }
    public void setJmbg(String value) {
        this.jmbg = value;
    }
    public String getBrojPasosa() {
        return brojPasosa;
    }
    public void setBrojPasosa(String value) {
        this.brojPasosa = value;
    }

    @Override
    public String toString() {
        final StringBuffer sb = new StringBuffer();
        sb.append("{tipDrzavljanstva: ").append(tipDrzavljanstva);
        if (!jmbg.isEmpty()) sb.append(", jmbg: '").append(jmbg).append('\'');
        if (!brojPasosa.isEmpty()) sb.append(", brojPasosa: '").append(brojPasosa).append('\'');
        sb.append("}");
        return sb.toString();
    }
}
