//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.10 at 05:55:13 PM CET 
//


package rs.tim14.xml.model.korisnici;

import javax.xml.bind.annotation.*;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TPravno_Lice", propOrder = {
        "poslovnoIme"
})
public class TPravnoLice
    extends TLice
{

    @XmlElement(name = "poslovno_ime", required = true)
    protected TPravnoLice.PoslovnoIme poslovnoIme;

    @Override
    public String getIme() {
        return getPoslovnoIme().getValue();
    }

    public TPravnoLice.PoslovnoIme getPoslovnoIme() {
        return poslovnoIme;
    }

    public void setPoslovnoIme(TPravnoLice.PoslovnoIme value) {
        this.poslovnoIme = value;
    }

    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "value"
    })
    public static class PoslovnoIme {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "property")
        @XmlSchemaType(name = "anySimpleType")
        protected String property;
        @XmlAttribute(name = "datatype")
        @XmlSchemaType(name = "anySimpleType")
        protected String datatype;
        public String getValue() {
            return value;
        }
        public void setValue(String value) {
            this.value = value;
        }
        public String getProperty() {
            return property;
        }

        public void setProperty(String value) {
            this.property = value;
        }
        public String getDatatype() {
            return datatype;
        }

        public void setDatatype(String value) {
            this.datatype = value;
        }

    }

    public String toString(String prefix) {
        final StringBuffer sb = new StringBuffer();
        sb.append("\n").append(prefix).append("Poslovno ime: '").append(poslovnoIme).append('\'');
        sb.append(super.toString(prefix));
        return sb.toString();
    }
}
