//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.10 at 05:55:13 PM CET 
//


package rs.tim14.xml.model.korisnici;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TFizicko_Lice", propOrder = {
    "punoIme",
    "drzavljanstvo"
})
public class TFizickoLice
    extends TLice
{

    @XmlElement(name = "puno_ime", required = true)
    protected PunoIme punoIme;
    protected Drzavljanstvo drzavljanstvo;
    public PunoIme getPunoIme() {
        return punoIme;
    }
    public void setPunoIme(PunoIme value) {
        this.punoIme = value;
    }
    public Drzavljanstvo getDrzavljanstvo() {
        return drzavljanstvo;
    }

    public void setDrzavljanstvo(Drzavljanstvo value) {
        this.drzavljanstvo = value;
    }

    @Override
    public String toString(String prefix) {
        final StringBuffer sb = new StringBuffer();
        sb.append("\n").append(prefix).append("Puno ime: ").append(punoIme);
        if (drzavljanstvo != null) sb.append("\n").append(prefix).append("Drzavljanstvo: ").append(drzavljanstvo);
        sb.append(super.toString(prefix));
        return sb.toString();
    }
}
