//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.11 at 12:57:05 AM CET 
//


package rs.tim14.xml.model.zahtev_za_priznanje_ziga;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rs.tim14.xml.zahtev_za_priznanje_ziga package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ZahtevZaPriznanjeZigaZnakVrstaZnakaDrugaVrstaZnaka_QNAME = new QName("http://www.xml.tim14.rs/zahtev_za_priznanje_ziga", "druga_vrsta_znaka");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rs.tim14.xml.zahtev_za_priznanje_ziga
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ZahtevZaPriznanjeZiga }
     * 
     */
    public ZahtevZaPriznanjeZiga createZahtevZaPriznanjeZiga() {
        return new ZahtevZaPriznanjeZiga();
    }

    /**
     * Create an instance of {@link ZahtevZaPriznanjeZiga.Znak }
     * 
     */
    public ZahtevZaPriznanjeZiga.Znak createZahtevZaPriznanjeZigaZnak() {
        return new ZahtevZaPriznanjeZiga.Znak();
    }

    /**
     * Create an instance of {@link ZahtevZaPriznanjeZiga.KlaseRobeIUsluga }
     * 
     */
    public ZahtevZaPriznanjeZiga.KlaseRobeIUsluga createZahtevZaPriznanjeZigaKlaseRobeIUsluga() {
        return new ZahtevZaPriznanjeZiga.KlaseRobeIUsluga();
    }

    /**
     * Create an instance of {@link ZahtevZaPriznanjeZiga.PravoPrvenstva }
     * 
     */
    public ZahtevZaPriznanjeZiga.PravoPrvenstva createZahtevZaPriznanjeZigaPravoPrvenstva() {
        return new ZahtevZaPriznanjeZiga.PravoPrvenstva();
    }

    /**
     * Create an instance of {@link ZahtevZaPriznanjeZiga.Takse }
     * 
     */
    public ZahtevZaPriznanjeZiga.Takse createZahtevZaPriznanjeZigaTakse() {
        return new ZahtevZaPriznanjeZiga.Takse();
    }

    /**
     * Create an instance of {@link ZahtevZaPriznanjeZiga.PriloziUzZahtev }
     * 
     */
    public ZahtevZaPriznanjeZiga.PriloziUzZahtev createZahtevZaPriznanjeZigaPriloziUzZahtev() {
        return new ZahtevZaPriznanjeZiga.PriloziUzZahtev();
    }

    /**
     * Create an instance of {@link ZahtevZaPriznanjeZiga.Znak.VrstaZnaka }
     * 
     */
    public ZahtevZaPriznanjeZiga.Znak.VrstaZnaka createZahtevZaPriznanjeZigaZnakVrstaZnaka() {
        return new ZahtevZaPriznanjeZiga.Znak.VrstaZnaka();
    }

    /**
     * Create an instance of {@link ZahtevZaPriznanjeZiga.Znak.BojeZnaka }
     * 
     */
    public ZahtevZaPriznanjeZiga.Znak.BojeZnaka createZahtevZaPriznanjeZigaZnakBojeZnaka() {
        return new ZahtevZaPriznanjeZiga.Znak.BojeZnaka();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.xml.tim14.rs/zahtev_za_priznanje_ziga", name = "druga_vrsta_znaka", scope = ZahtevZaPriznanjeZiga.Znak.VrstaZnaka.class)
    public JAXBElement<String> createZahtevZaPriznanjeZigaZnakVrstaZnakaDrugaVrstaZnaka(String value) {
        return new JAXBElement<String>(_ZahtevZaPriznanjeZigaZnakVrstaZnakaDrugaVrstaZnaka_QNAME, String.class, ZahtevZaPriznanjeZiga.Znak.VrstaZnaka.class, value);
    }

}
