//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.10 at 05:55:13 PM CET 
//


package rs.tim14.xml.model.zahtev_za_priznanje_ziga;

import javax.xml.bind.annotation.*;
import java.math.BigInteger;
import java.util.Date;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TPrijava", propOrder = {
    "brojPrijave",
    "datumPodnosenja"
})
public class TPrijava {

    @XmlElement(name = "broj_prijave", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger brojPrijave;
    @XmlElement(name = "datum_podnosenja", required = true)
    @XmlSchemaType(name = "date")
    protected Date datumPodnosenja;

    public BigInteger getBrojPrijave() {
        return brojPrijave;
    }

    public void setBrojPrijave(BigInteger value) {
        this.brojPrijave = value;
    }

    public Date getDatumPodnosenja() {
        return datumPodnosenja;
    }

    public void setDatumPodnosenja(Date value) {
        this.datumPodnosenja = value;
    }


    @Override
    public String toString() {
        final StringBuffer sb = new StringBuffer("{");
        sb.append("broj prijave: ").append(brojPrijave);
        if (datumPodnosenja != null) sb.append(", datum podnosenja: ").append(datumPodnosenja);
        sb.append('}');
        return sb.toString();
    }
}
