//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.11 at 12:43:21 PM CET 
//


package rs.tim14.xml.model.zahtev_za_priznanje_ziga;

import rs.tim14.xml.model.korisnici.TLice;

import java.io.Serializable;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlMixed;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="podnosilac" type="{http://www.xml.tim14.rs/korisnici}TLice"/>
 *         &lt;element name="punomocnik" type="{http://www.xml.tim14.rs/korisnici}TLice"/>
 *         &lt;element name="zajednicki_predstavnik" type="{http://www.xml.tim14.rs/korisnici}TLice" minOccurs="0"/>
 *         &lt;element name="vrsta_ziga" type="{http://www.xml.tim14.rs/zahtev_za_priznanje_ziga}TVrsta_ziga"/>
 *         &lt;element name="znak">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="vrsta_znaka">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence minOccurs="0">
 *                             &lt;element name="druga_vrsta_znaka" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="vrsta_znaka" type="{http://www.xml.tim14.rs/zahtev_za_priznanje_ziga}TVrsta_znaka" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="izgled_znaka" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;sequence>
 *                     &lt;element name="boje_znaka" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *                   &lt;/sequence>
 *                   &lt;element name="transliteracija_znaka" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="prevod_znaka" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="opis_znaka" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;sequence>
 *           &lt;element name="klase_robe_ili_usluge" type="{http://www.xml.tim14.rs/zahtev_za_priznanje_ziga}TKlasa_robe" maxOccurs="45"/>
 *         &lt;/sequence>
 *         &lt;element name="pravo_prvenstva">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence minOccurs="0">
 *                   &lt;element name="osnov_prava_prvenstva" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="zatrazeno_pravo_prvenstva" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="takse">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="osnovna_taksa" type="{http://www.xml.tim14.rs/zahtev_za_priznanje_ziga}TTaksa"/>
 *                   &lt;element name="taksa_za_klase" type="{http://www.xml.tim14.rs/zahtev_za_priznanje_ziga}TTaksa"/>
 *                   &lt;element name="taksa_za_graficko_resenje" type="{http://www.xml.tim14.rs/zahtev_za_priznanje_ziga}TTaksa"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="ukupna_vrednost" use="required" type="{http://www.xml.tim14.rs/zahtev_za_priznanje_ziga}TTaksa" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Prilozi_uz_zahtev">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="primerak_znaka" type="{http://www.xml.tim14.rs/zahtev_za_priznanje_ziga}TPrilog" minOccurs="0"/>
 *                   &lt;element name="spisak_robe_i_usluga" type="{http://www.xml.tim14.rs/zahtev_za_priznanje_ziga}TPrilog" minOccurs="0"/>
 *                   &lt;element name="punomocje" type="{http://www.xml.tim14.rs/zahtev_za_priznanje_ziga}TPrilog" minOccurs="0"/>
 *                   &lt;element name="generalno_punomocje" type="{http://www.xml.tim14.rs/zahtev_za_priznanje_ziga}TPrilog" minOccurs="0"/>
 *                   &lt;element name="naknadno_punomocje" type="{http://www.xml.tim14.rs/zahtev_za_priznanje_ziga}TPrilog" minOccurs="0"/>
 *                   &lt;element name="akti_o_kolektivnom_zig_ili_zigu_garancije" type="{http://www.xml.tim14.rs/zahtev_za_priznanje_ziga}TPrilog" minOccurs="0"/>
 *                   &lt;element name="dokaz_o_pravu_prvenstva" type="{http://www.xml.tim14.rs/zahtev_za_priznanje_ziga}TPrilog" minOccurs="0"/>
 *                   &lt;element name="dokaz_o_uplati_takse" type="{http://www.xml.tim14.rs/zahtev_za_priznanje_ziga}TPrilog" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="broj_prijave" use="required" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
 *       &lt;attribute name="datum_podnosenja" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "podnosilac",
    "punomocnik",
    "zajednickiPredstavnik",
    "vrstaZiga",
    "znak",
    "klaseRobeIliUsluge",
    "pravoPrvenstva",
    "takse",
    "priloziUzZahtev"
})
@XmlRootElement(name = "zahtev_za_priznanje_ziga")
public class ZahtevZaPriznanjeZiga {

    @XmlElement(required = true)
    protected TLice podnosilac;
    @XmlElement(required = true)
    protected TLice punomocnik;
    @XmlElement(name = "zajednicki_predstavnik")
    protected TLice zajednickiPredstavnik;
    @XmlElement(name = "vrsta_ziga", required = true)
    protected TVrstaZiga vrstaZiga;
    @XmlElement(required = true)
    protected Znak znak;
    @XmlElement(name = "klase_robe_ili_usluge", type = Integer.class)
    protected List<Integer> klaseRobeIliUsluge;
    @XmlElement(name = "pravo_prvenstva", required = true)
    protected PravoPrvenstva pravoPrvenstva;
    @XmlElement(required = true)
    protected Takse takse;
    @XmlElement(name = "Prilozi_uz_zahtev", required = true)
    protected PriloziUzZahtev priloziUzZahtev;
    @XmlAttribute(name = "broj_prijave", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger brojPrijave;
    @XmlAttribute(name = "datum_podnosenja", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datumPodnosenja;

    /**
     * Gets the value of the podnosilac property.
     * 
     * @return
     *     possible object is
     *     {@link TLice }
     *     
     */
    public TLice getPodnosilac() {
        return podnosilac;
    }

    /**
     * Sets the value of the podnosilac property.
     * 
     * @param value
     *     allowed object is
     *     {@link TLice }
     *     
     */
    public void setPodnosilac(TLice value) {
        this.podnosilac = value;
    }

    /**
     * Gets the value of the punomocnik property.
     * 
     * @return
     *     possible object is
     *     {@link TLice }
     *     
     */
    public TLice getPunomocnik() {
        return punomocnik;
    }

    /**
     * Sets the value of the punomocnik property.
     * 
     * @param value
     *     allowed object is
     *     {@link TLice }
     *     
     */
    public void setPunomocnik(TLice value) {
        this.punomocnik = value;
    }

    /**
     * Gets the value of the zajednickiPredstavnik property.
     * 
     * @return
     *     possible object is
     *     {@link TLice }
     *     
     */
    public TLice getZajednickiPredstavnik() {
        return zajednickiPredstavnik;
    }

    /**
     * Sets the value of the zajednickiPredstavnik property.
     * 
     * @param value
     *     allowed object is
     *     {@link TLice }
     *     
     */
    public void setZajednickiPredstavnik(TLice value) {
        this.zajednickiPredstavnik = value;
    }

    /**
     * Gets the value of the vrstaZiga property.
     * 
     * @return
     *     possible object is
     *     {@link TVrstaZiga }
     *     
     */
    public TVrstaZiga getVrstaZiga() {
        return vrstaZiga;
    }

    /**
     * Sets the value of the vrstaZiga property.
     * 
     * @param value
     *     allowed object is
     *     {@link TVrstaZiga }
     *     
     */
    public void setVrstaZiga(TVrstaZiga value) {
        this.vrstaZiga = value;
    }

    /**
     * Gets the value of the znak property.
     * 
     * @return
     *     possible object is
     *     {@link Znak }
     *     
     */
    public Znak getZnak() {
        return znak;
    }

    /**
     * Sets the value of the znak property.
     * 
     * @param value
     *     allowed object is
     *     {@link Znak }
     *     
     */
    public void setZnak(Znak value) {
        this.znak = value;
    }

    /**
     * Gets the value of the klaseRobeIliUsluge property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the klaseRobeIliUsluge property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getKlaseRobeIliUsluge().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Integer }
     * 
     * 
     */
    public List<Integer> getKlaseRobeIliUsluge() {
        if (klaseRobeIliUsluge == null) {
            klaseRobeIliUsluge = new ArrayList<Integer>();
        }
        return this.klaseRobeIliUsluge;
    }

    /**
     * Gets the value of the pravoPrvenstva property.
     * 
     * @return
     *     possible object is
     *     {@link PravoPrvenstva }
     *     
     */
    public PravoPrvenstva getPravoPrvenstva() {
        return pravoPrvenstva;
    }

    /**
     * Sets the value of the pravoPrvenstva property.
     * 
     * @param value
     *     allowed object is
     *     {@link PravoPrvenstva }
     *     
     */
    public void setPravoPrvenstva(PravoPrvenstva value) {
        this.pravoPrvenstva = value;
    }

    /**
     * Gets the value of the takse property.
     * 
     * @return
     *     possible object is
     *     {@link Takse }
     *     
     */
    public Takse getTakse() {
        return takse;
    }

    /**
     * Sets the value of the takse property.
     * 
     * @param value
     *     allowed object is
     *     {@link Takse }
     *     
     */
    public void setTakse(Takse value) {
        this.takse = value;
    }

    /**
     * Gets the value of the priloziUzZahtev property.
     * 
     * @return
     *     possible object is
     *     {@link PriloziUzZahtev }
     *     
     */
    public PriloziUzZahtev getPriloziUzZahtev() {
        return priloziUzZahtev;
    }

    /**
     * Sets the value of the priloziUzZahtev property.
     * 
     * @param value
     *     allowed object is
     *     {@link PriloziUzZahtev }
     *     
     */
    public void setPriloziUzZahtev(PriloziUzZahtev value) {
        this.priloziUzZahtev = value;
    }

    /**
     * Gets the value of the brojPrijave property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getBrojPrijave() {
        return brojPrijave;
    }

    /**
     * Sets the value of the brojPrijave property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setBrojPrijave(BigInteger value) {
        this.brojPrijave = value;
    }

    /**
     * Gets the value of the datumPodnosenja property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumPodnosenja() {
        return datumPodnosenja;
    }

    /**
     * Sets the value of the datumPodnosenja property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumPodnosenja(XMLGregorianCalendar value) {
        this.datumPodnosenja = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence minOccurs="0">
     *         &lt;element name="osnov_prava_prvenstva" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="zatrazeno_pravo_prvenstva" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "osnovPravaPrvenstva"
    })
    public static class PravoPrvenstva {

        @XmlElement(name = "osnov_prava_prvenstva")
        protected String osnovPravaPrvenstva;
        @XmlAttribute(name = "zatrazeno_pravo_prvenstva", required = true)
        protected boolean zatrazenoPravoPrvenstva;

        /**
         * Gets the value of the osnovPravaPrvenstva property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOsnovPravaPrvenstva() {
            return osnovPravaPrvenstva;
        }

        /**
         * Sets the value of the osnovPravaPrvenstva property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOsnovPravaPrvenstva(String value) {
            this.osnovPravaPrvenstva = value;
        }

        /**
         * Gets the value of the zatrazenoPravoPrvenstva property.
         * 
         */
        public boolean isZatrazenoPravoPrvenstva() {
            return zatrazenoPravoPrvenstva;
        }

        /**
         * Sets the value of the zatrazenoPravoPrvenstva property.
         * 
         */
        public void setZatrazenoPravoPrvenstva(boolean value) {
            this.zatrazenoPravoPrvenstva = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="primerak_znaka" type="{http://www.xml.tim14.rs/zahtev_za_priznanje_ziga}TPrilog" minOccurs="0"/>
     *         &lt;element name="spisak_robe_i_usluga" type="{http://www.xml.tim14.rs/zahtev_za_priznanje_ziga}TPrilog" minOccurs="0"/>
     *         &lt;element name="punomocje" type="{http://www.xml.tim14.rs/zahtev_za_priznanje_ziga}TPrilog" minOccurs="0"/>
     *         &lt;element name="generalno_punomocje" type="{http://www.xml.tim14.rs/zahtev_za_priznanje_ziga}TPrilog" minOccurs="0"/>
     *         &lt;element name="naknadno_punomocje" type="{http://www.xml.tim14.rs/zahtev_za_priznanje_ziga}TPrilog" minOccurs="0"/>
     *         &lt;element name="akti_o_kolektivnom_zig_ili_zigu_garancije" type="{http://www.xml.tim14.rs/zahtev_za_priznanje_ziga}TPrilog" minOccurs="0"/>
     *         &lt;element name="dokaz_o_pravu_prvenstva" type="{http://www.xml.tim14.rs/zahtev_za_priznanje_ziga}TPrilog" minOccurs="0"/>
     *         &lt;element name="dokaz_o_uplati_takse" type="{http://www.xml.tim14.rs/zahtev_za_priznanje_ziga}TPrilog" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "primerakZnaka",
        "spisakRobeIUsluga",
        "punomocje",
        "generalnoPunomocje",
        "naknadnoPunomocje",
        "aktiOKolektivnomZigIliZiguGarancije",
        "dokazOPravuPrvenstva",
        "dokazOUplatiTakse"
    })
    public static class PriloziUzZahtev {

        @XmlElement(name = "primerak_znaka")
        protected String primerakZnaka;
        @XmlElement(name = "spisak_robe_i_usluga")
        protected String spisakRobeIUsluga;
        protected String punomocje;
        @XmlElement(name = "generalno_punomocje")
        protected String generalnoPunomocje;
        @XmlElement(name = "naknadno_punomocje")
        protected String naknadnoPunomocje;
        @XmlElement(name = "akti_o_kolektivnom_zig_ili_zigu_garancije")
        protected String aktiOKolektivnomZigIliZiguGarancije;
        @XmlElement(name = "dokaz_o_pravu_prvenstva")
        protected String dokazOPravuPrvenstva;
        @XmlElement(name = "dokaz_o_uplati_takse")
        protected String dokazOUplatiTakse;

        /**
         * Gets the value of the primerakZnaka property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPrimerakZnaka() {
            return primerakZnaka;
        }

        /**
         * Sets the value of the primerakZnaka property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPrimerakZnaka(String value) {
            this.primerakZnaka = value;
        }

        /**
         * Gets the value of the spisakRobeIUsluga property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSpisakRobeIUsluga() {
            return spisakRobeIUsluga;
        }

        /**
         * Sets the value of the spisakRobeIUsluga property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSpisakRobeIUsluga(String value) {
            this.spisakRobeIUsluga = value;
        }

        /**
         * Gets the value of the punomocje property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPunomocje() {
            return punomocje;
        }

        /**
         * Sets the value of the punomocje property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPunomocje(String value) {
            this.punomocje = value;
        }

        /**
         * Gets the value of the generalnoPunomocje property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getGeneralnoPunomocje() {
            return generalnoPunomocje;
        }

        /**
         * Sets the value of the generalnoPunomocje property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setGeneralnoPunomocje(String value) {
            this.generalnoPunomocje = value;
        }

        /**
         * Gets the value of the naknadnoPunomocje property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNaknadnoPunomocje() {
            return naknadnoPunomocje;
        }

        /**
         * Sets the value of the naknadnoPunomocje property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNaknadnoPunomocje(String value) {
            this.naknadnoPunomocje = value;
        }

        /**
         * Gets the value of the aktiOKolektivnomZigIliZiguGarancije property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAktiOKolektivnomZigIliZiguGarancije() {
            return aktiOKolektivnomZigIliZiguGarancije;
        }

        /**
         * Sets the value of the aktiOKolektivnomZigIliZiguGarancije property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAktiOKolektivnomZigIliZiguGarancije(String value) {
            this.aktiOKolektivnomZigIliZiguGarancije = value;
        }

        /**
         * Gets the value of the dokazOPravuPrvenstva property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDokazOPravuPrvenstva() {
            return dokazOPravuPrvenstva;
        }

        /**
         * Sets the value of the dokazOPravuPrvenstva property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDokazOPravuPrvenstva(String value) {
            this.dokazOPravuPrvenstva = value;
        }

        /**
         * Gets the value of the dokazOUplatiTakse property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDokazOUplatiTakse() {
            return dokazOUplatiTakse;
        }

        /**
         * Sets the value of the dokazOUplatiTakse property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDokazOUplatiTakse(String value) {
            this.dokazOUplatiTakse = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="osnovna_taksa" type="{http://www.xml.tim14.rs/zahtev_za_priznanje_ziga}TTaksa"/>
     *         &lt;element name="taksa_za_klase" type="{http://www.xml.tim14.rs/zahtev_za_priznanje_ziga}TTaksa"/>
     *         &lt;element name="taksa_za_graficko_resenje" type="{http://www.xml.tim14.rs/zahtev_za_priznanje_ziga}TTaksa"/>
     *       &lt;/sequence>
     *       &lt;attribute name="ukupna_vrednost" use="required" type="{http://www.xml.tim14.rs/zahtev_za_priznanje_ziga}TTaksa" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "osnovnaTaksa",
        "taksaZaKlase",
        "taksaZaGrafickoResenje"
    })
    public static class Takse {

        @XmlElement(name = "osnovna_taksa")
        protected double osnovnaTaksa;
        @XmlElement(name = "taksa_za_klase")
        protected double taksaZaKlase;
        @XmlElement(name = "taksa_za_graficko_resenje")
        protected double taksaZaGrafickoResenje;
        @XmlAttribute(name = "ukupna_vrednost", required = true)
        protected double ukupnaVrednost;

        /**
         * Gets the value of the osnovnaTaksa property.
         * 
         */
        public double getOsnovnaTaksa() {
            return osnovnaTaksa;
        }

        /**
         * Sets the value of the osnovnaTaksa property.
         * 
         */
        public void setOsnovnaTaksa(double value) {
            this.osnovnaTaksa = value;
        }

        /**
         * Gets the value of the taksaZaKlase property.
         * 
         */
        public double getTaksaZaKlase() {
            return taksaZaKlase;
        }

        /**
         * Sets the value of the taksaZaKlase property.
         * 
         */
        public void setTaksaZaKlase(double value) {
            this.taksaZaKlase = value;
        }

        /**
         * Gets the value of the taksaZaGrafickoResenje property.
         * 
         */
        public double getTaksaZaGrafickoResenje() {
            return taksaZaGrafickoResenje;
        }

        /**
         * Sets the value of the taksaZaGrafickoResenje property.
         * 
         */
        public void setTaksaZaGrafickoResenje(double value) {
            this.taksaZaGrafickoResenje = value;
        }

        /**
         * Gets the value of the ukupnaVrednost property.
         * 
         */
        public double getUkupnaVrednost() {
            return ukupnaVrednost;
        }

        /**
         * Sets the value of the ukupnaVrednost property.
         * 
         */
        public void setUkupnaVrednost(double value) {
            this.ukupnaVrednost = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="vrsta_znaka">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence minOccurs="0">
     *                   &lt;element name="druga_vrsta_znaka" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="vrsta_znaka" type="{http://www.xml.tim14.rs/zahtev_za_priznanje_ziga}TVrsta_znaka" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="izgled_znaka" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;sequence>
     *           &lt;element name="boje_znaka" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
     *         &lt;/sequence>
     *         &lt;element name="transliteracija_znaka" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="prevod_znaka" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="opis_znaka" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "vrstaZnaka",
        "izgledZnaka",
        "bojeZnaka",
        "transliteracijaZnaka",
        "prevodZnaka",
        "opisZnaka"
    })
    public static class Znak {

        @XmlElement(name = "vrsta_znaka", required = true)
        protected VrstaZnaka vrstaZnaka;
        @XmlElement(name = "izgled_znaka", required = true)
        protected String izgledZnaka;
        @XmlElement(name = "boje_znaka", required = true)
        protected List<String> bojeZnaka;
        @XmlElement(name = "transliteracija_znaka")
        protected String transliteracijaZnaka;
        @XmlElement(name = "prevod_znaka")
        protected String prevodZnaka;
        @XmlElement(name = "opis_znaka", required = true)
        protected String opisZnaka;

        /**
         * Gets the value of the vrstaZnaka property.
         * 
         * @return
         *     possible object is
         *     {@link VrstaZnaka }
         *     
         */
        public VrstaZnaka getVrstaZnaka() {
            return vrstaZnaka;
        }

        /**
         * Sets the value of the vrstaZnaka property.
         * 
         * @param value
         *     allowed object is
         *     {@link VrstaZnaka }
         *     
         */
        public void setVrstaZnaka(VrstaZnaka value) {
            this.vrstaZnaka = value;
        }

        /**
         * Gets the value of the izgledZnaka property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIzgledZnaka() {
            return izgledZnaka;
        }

        /**
         * Sets the value of the izgledZnaka property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIzgledZnaka(String value) {
            this.izgledZnaka = value;
        }

        /**
         * Gets the value of the bojeZnaka property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the bojeZnaka property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getBojeZnaka().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getBojeZnaka() {
            if (bojeZnaka == null) {
                bojeZnaka = new ArrayList<String>();
            }
            return this.bojeZnaka;
        }

        /**
         * Gets the value of the transliteracijaZnaka property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTransliteracijaZnaka() {
            return transliteracijaZnaka;
        }

        /**
         * Sets the value of the transliteracijaZnaka property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTransliteracijaZnaka(String value) {
            this.transliteracijaZnaka = value;
        }

        /**
         * Gets the value of the prevodZnaka property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPrevodZnaka() {
            return prevodZnaka;
        }

        /**
         * Sets the value of the prevodZnaka property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPrevodZnaka(String value) {
            this.prevodZnaka = value;
        }

        /**
         * Gets the value of the opisZnaka property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOpisZnaka() {
            return opisZnaka;
        }

        /**
         * Sets the value of the opisZnaka property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOpisZnaka(String value) {
            this.opisZnaka = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence minOccurs="0">
         *         &lt;element name="druga_vrsta_znaka" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *       &lt;attribute name="vrsta_znaka" type="{http://www.xml.tim14.rs/zahtev_za_priznanje_ziga}TVrsta_znaka" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "content"
        })
        public static class VrstaZnaka {

            @XmlElementRef(name = "druga_vrsta_znaka", namespace = "http://www.xml.tim14.rs/zahtev_za_priznanje_ziga", type = JAXBElement.class, required = false)
            @XmlMixed
            protected List<Serializable> content;
            @XmlAttribute(name = "vrsta_znaka")
            protected TVrstaZnaka vrstaZnaka;

            /**
             * Gets the value of the content property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the content property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getContent().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link JAXBElement }{@code <}{@link String }{@code >}
             * {@link String }
             * 
             * 
             */
            public List<Serializable> getContent() {
                if (content == null) {
                    content = new ArrayList<Serializable>();
                }
                return this.content;
            }

            /**
             * Gets the value of the vrstaZnaka property.
             * 
             * @return
             *     possible object is
             *     {@link TVrstaZnaka }
             *     
             */
            public TVrstaZnaka getVrstaZnaka() {
                return vrstaZnaka;
            }

            /**
             * Sets the value of the vrstaZnaka property.
             * 
             * @param value
             *     allowed object is
             *     {@link TVrstaZnaka }
             *     
             */
            public void setVrstaZnaka(TVrstaZnaka value) {
                this.vrstaZnaka = value;
            }

        }

    }

}
