//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.11 at 12:43:21 PM CET 
//


package rs.tim14.xml.model.zahtev_za_priznanje_ziga;

import rs.tim14.xml.model.korisnici.TLice;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "prijava",
    "podnosilac",
    "punomocnik",
    "zajednickiPredstavnik",
    "vrstaZiga",
    "znak",
    "klaseRobeIliUsluge",
    "pravoPrvenstva",
    "takse",
    "priloziUzZahtev"
})
@XmlRootElement(name = "zahtev_za_priznanje_ziga")
public class ZahtevZaPriznanjeZiga {

    @XmlElement(required = true)
    protected TPrijava prijava;

    @XmlElement(required = true)
    protected TLice podnosilac;
    @XmlElement(required = true)
    protected TLice punomocnik;
    @XmlElement(name = "zajednicki_predstavnik")
    protected TLice zajednickiPredstavnik;
    @XmlElement(name = "vrsta_ziga", required = true)
    protected VrstaZiga vrstaZiga;
    @XmlElement(required = true)
    protected Znak znak;
    @XmlElement(name = "klase_robe_ili_usluge", type = Integer.class)
    protected List<Integer> klaseRobeIliUsluge;
    @XmlElement(name = "pravo_prvenstva", required = true)
    protected PravoPrvenstva pravoPrvenstva;
    @XmlElement(required = true)
    protected Takse takse;
    @XmlElement(name = "Prilozi_uz_zahtev", required = true)
    protected PriloziUzZahtev priloziUzZahtev;

    @XmlAnyAttribute
    private Map<QName, String> references = new HashMap<QName, String>();

    public Map<QName, String> getReferences() {
        return references;
    }


    public TPrijava getPrijava() {
        return prijava;
    }
    public void setPrijava(TPrijava value) {
        this.prijava = value;
    }


    public TLice getPodnosilac() {
        return podnosilac;
    }
    public void setPodnosilac(TLice value) {
        this.podnosilac = value;
    }
    public TLice getPunomocnik() {
        return punomocnik;
    }
    public void setPunomocnik(TLice value) {
        this.punomocnik = value;
    }
    public TLice getZajednickiPredstavnik() {
        return zajednickiPredstavnik;
    }
    public void setZajednickiPredstavnik(TLice value) {
        this.zajednickiPredstavnik = value;
    }
    public ZahtevZaPriznanjeZiga.VrstaZiga getVrstaZiga() {
        return vrstaZiga;
    }
    public void setVrstaZiga(ZahtevZaPriznanjeZiga.VrstaZiga value) {
        this.vrstaZiga = value;
    }
    public Znak getZnak() {
        return znak;
    }
    public void setZnak(Znak value) {
        this.znak = value;
    }
    public List<Integer> getKlaseRobeIliUsluge() {
        if (klaseRobeIliUsluge == null) {
            klaseRobeIliUsluge = new ArrayList<Integer>();
        }
        return this.klaseRobeIliUsluge;
    }
    public PravoPrvenstva getPravoPrvenstva() {
        return pravoPrvenstva;
    }
    public void setPravoPrvenstva(PravoPrvenstva value) {
        this.pravoPrvenstva = value;
    }
    public Takse getTakse() {
        return takse;
    }
    public void setTakse(Takse value) {
        this.takse = value;
    }
    public PriloziUzZahtev getPriloziUzZahtev() {
        return priloziUzZahtev;
    }
    public void setPriloziUzZahtev(PriloziUzZahtev value) {
        this.priloziUzZahtev = value;
    }

    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "value"
    })
    public static class VrstaZiga {

        @XmlValue
        protected TVrstaZiga value;
        @XmlAttribute(name = "property")
        @XmlSchemaType(name = "anySimpleType")
        protected String property;
        @XmlAttribute(name = "datatype")
        @XmlSchemaType(name = "anySimpleType")
        protected String datatype;


        public TVrstaZiga getValue() {
            return value;
        }


        public void setValue(TVrstaZiga value) {
            this.value = value;
        }


        public String getProperty() {
            return property;
        }


        public void setProperty(String value) {
            this.property = value;
        }

        public String getDatatype() {
            return datatype;
        }

        public void setDatatype(String value) {
            this.datatype = value;
        }

    }

    @Override
    public String toString() {
        final StringBuffer sb = new StringBuffer("Zahtev za priznanje ziga: ");
        sb.append("\n\tPodnosilac: ").append(podnosilac.toString("\t\t"));
        sb.append("\n\tPunomocnik: ").append(punomocnik.toString("\t\t"));
        if (zajednickiPredstavnik != null) sb.append("\n\tZajednicki predstavnik: ").append(zajednickiPredstavnik);
        sb.append("\n\tVrsta ziga: ").append(vrstaZiga);
        sb.append("\n\tZnak: ").append(znak);
        sb.append("\n\tKlase robe ili usluge: ").append(klaseRobeIliUsluge);
        sb.append("\n\tPravo prvenstva: ").append(pravoPrvenstva);
        sb.append("\n\tTakse: ").append(takse);
        sb.append("\n\tPrilozi uz zahtev: ").append(priloziUzZahtev);
        sb.append("\n\tBroj prijave: ").append(prijava.brojPrijave);
        sb.append("\n\tDatum podnosenja: ").append(prijava.datumPodnosenja);
        return sb.toString();
    }


}
