//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.11 at 12:43:21 PM CET 
//


package rs.tim14.xml.model.zahtev_za_priznanje_ziga;

import rs.tim14.xml.model.korisnici.TLice;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="podnosilac" type="{http://www.xml.tim14.rs/korisnici}TLice"/>
 *         &lt;element name="punomocnik" type="{http://www.xml.tim14.rs/korisnici}TLice"/>
 *         &lt;element name="zajednicki_predstavnik" type="{http://www.xml.tim14.rs/korisnici}TLice" minOccurs="0"/>
 *         &lt;element name="vrsta_ziga" type="{http://www.xml.tim14.rs/zahtev_za_priznanje_ziga}TVrsta_ziga"/>
 *         &lt;element name="znak">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="vrsta_znaka">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence minOccurs="0">
 *                             &lt;element name="druga_vrsta_znaka" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="vrsta_znaka" type="{http://www.xml.tim14.rs/zahtev_za_priznanje_ziga}TVrsta_znaka" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="izgled_znaka" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;sequence>
 *                     &lt;element name="boje_znaka" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *                   &lt;/sequence>
 *                   &lt;element name="transliteracija_znaka" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="prevod_znaka" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="opis_znaka" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;sequence>
 *           &lt;element name="klase_robe_ili_usluge" type="{http://www.xml.tim14.rs/zahtev_za_priznanje_ziga}TKlasa_robe" maxOccurs="45"/>
 *         &lt;/sequence>
 *         &lt;element name="pravo_prvenstva">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence minOccurs="0">
 *                   &lt;element name="osnov_prava_prvenstva" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="zatrazeno_pravo_prvenstva" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="takse">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="osnovna_taksa" type="{http://www.xml.tim14.rs/zahtev_za_priznanje_ziga}TTaksa"/>
 *                   &lt;element name="taksa_za_klase" type="{http://www.xml.tim14.rs/zahtev_za_priznanje_ziga}TTaksa"/>
 *                   &lt;element name="taksa_za_graficko_resenje" type="{http://www.xml.tim14.rs/zahtev_za_priznanje_ziga}TTaksa"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="ukupna_vrednost" use="required" type="{http://www.xml.tim14.rs/zahtev_za_priznanje_ziga}TTaksa" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Prilozi_uz_zahtev">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="primerak_znaka" type="{http://www.xml.tim14.rs/zahtev_za_priznanje_ziga}TPrilog" minOccurs="0"/>
 *                   &lt;element name="spisak_robe_i_usluga" type="{http://www.xml.tim14.rs/zahtev_za_priznanje_ziga}TPrilog" minOccurs="0"/>
 *                   &lt;element name="punomocje" type="{http://www.xml.tim14.rs/zahtev_za_priznanje_ziga}TPrilog" minOccurs="0"/>
 *                   &lt;element name="generalno_punomocje" type="{http://www.xml.tim14.rs/zahtev_za_priznanje_ziga}TPrilog" minOccurs="0"/>
 *                   &lt;element name="naknadno_punomocje" type="{http://www.xml.tim14.rs/zahtev_za_priznanje_ziga}TPrilog" minOccurs="0"/>
 *                   &lt;element name="akti_o_kolektivnom_zig_ili_zigu_garancije" type="{http://www.xml.tim14.rs/zahtev_za_priznanje_ziga}TPrilog" minOccurs="0"/>
 *                   &lt;element name="dokaz_o_pravu_prvenstva" type="{http://www.xml.tim14.rs/zahtev_za_priznanje_ziga}TPrilog" minOccurs="0"/>
 *                   &lt;element name="dokaz_o_uplati_takse" type="{http://www.xml.tim14.rs/zahtev_za_priznanje_ziga}TPrilog" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="broj_prijave" use="required" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
 *       &lt;attribute name="datum_podnosenja" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "podnosilac",
    "punomocnik",
    "zajednickiPredstavnik",
    "vrstaZiga",
    "znak",
    "klaseRobeIliUsluge",
    "pravoPrvenstva",
    "takse",
    "priloziUzZahtev"
})
@XmlRootElement(name = "zahtev_za_priznanje_ziga")
public class ZahtevZaPriznanjeZiga {

    @XmlElement(required = true)
    protected TLice podnosilac;
    @XmlElement(required = true)
    protected TLice punomocnik;
    @XmlElement(name = "zajednicki_predstavnik")
    protected TLice zajednickiPredstavnik;
    @XmlElement(name = "vrsta_ziga", required = true)
    protected TVrstaZiga vrstaZiga;
    @XmlElement(required = true)
    protected Znak znak;
    @XmlElement(name = "klase_robe_ili_usluge", type = Integer.class)
    protected List<Integer> klaseRobeIliUsluge;
    @XmlElement(name = "pravo_prvenstva", required = true)
    protected PravoPrvenstva pravoPrvenstva;
    @XmlElement(required = true)
    protected Takse takse;
    @XmlElement(name = "Prilozi_uz_zahtev", required = true)
    protected PriloziUzZahtev priloziUzZahtev;
    @XmlAttribute(name = "broj_prijave", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger brojPrijave;
    @XmlAttribute(name = "datum_podnosenja", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datumPodnosenja;

    public TLice getPodnosilac() {
        return podnosilac;
    }
    public void setPodnosilac(TLice value) {
        this.podnosilac = value;
    }
    public TLice getPunomocnik() {
        return punomocnik;
    }
    public void setPunomocnik(TLice value) {
        this.punomocnik = value;
    }
    public TLice getZajednickiPredstavnik() {
        return zajednickiPredstavnik;
    }
    public void setZajednickiPredstavnik(TLice value) {
        this.zajednickiPredstavnik = value;
    }
    public TVrstaZiga getVrstaZiga() {
        return vrstaZiga;
    }
    public void setVrstaZiga(TVrstaZiga value) {
        this.vrstaZiga = value;
    }
    public Znak getZnak() {
        return znak;
    }
    public void setZnak(Znak value) {
        this.znak = value;
    }
    public List<Integer> getKlaseRobeIliUsluge() {
        if (klaseRobeIliUsluge == null) {
            klaseRobeIliUsluge = new ArrayList<Integer>();
        }
        return this.klaseRobeIliUsluge;
    }
    public PravoPrvenstva getPravoPrvenstva() {
        return pravoPrvenstva;
    }
    public void setPravoPrvenstva(PravoPrvenstva value) {
        this.pravoPrvenstva = value;
    }
    public Takse getTakse() {
        return takse;
    }
    public void setTakse(Takse value) {
        this.takse = value;
    }
    public PriloziUzZahtev getPriloziUzZahtev() {
        return priloziUzZahtev;
    }
    public void setPriloziUzZahtev(PriloziUzZahtev value) {
        this.priloziUzZahtev = value;
    }
    public BigInteger getBrojPrijave() {
        return brojPrijave;
    }
    public void setBrojPrijave(BigInteger value) {
        this.brojPrijave = value;
    }
    public XMLGregorianCalendar getDatumPodnosenja() {
        return datumPodnosenja;
    }
    public void setDatumPodnosenja(XMLGregorianCalendar value) {
        this.datumPodnosenja = value;
    }

    @Override
    public String toString() {
        final StringBuffer sb = new StringBuffer("Zahtev za priznanje ziga: ");
        sb.append("\n\tPodnosilac: ").append(podnosilac.toString("\t\t"));
        sb.append("\n\tPunomocnik: ").append(punomocnik.toString("\t\t"));
        if (zajednickiPredstavnik != null) sb.append("\n\tZajednicki predstavnik: ").append(zajednickiPredstavnik);
        sb.append("\n\tVrsta ziga: ").append(vrstaZiga);
        sb.append("\n\tZnak: ").append(znak);
        sb.append("\n\tKlase robe ili usluge: ").append(klaseRobeIliUsluge);
        sb.append("\n\tPravo prvenstva: ").append(pravoPrvenstva);
        sb.append("\n\tTakse: ").append(takse);
        sb.append("\n\tPrilozi uz zahtev: ").append(priloziUzZahtev);
        sb.append("\n\tBroj prijave: ").append(brojPrijave);
        sb.append("\n\tDatum podnosenja: ").append(datumPodnosenja);
        return sb.toString();
    }


}
