//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.10 at 05:55:13 PM CET 
//


package rs.tim14.xml.model.korisnici;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="tip_drzavljanstva" type="{http://www.xml.tim14.rs/korisnici}TTip_drzavljanstva"/>
 *         &lt;element name="jmbg">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.xml.tim14.rs/korisnici}TJmbg">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="broj_pasosa" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "tipDrzavljanstva",
    "jmbg",
    "brojPasosa"
})
@XmlRootElement(name = "drzavljanstvo")
public class Drzavljanstvo {

    @XmlElement(name = "tip_drzavljanstva", required = true)
    protected TTipDrzavljanstva tipDrzavljanstva;
    @XmlElement(required = true)
    protected String jmbg;
    @XmlElement(name = "broj_pasosa", required = true)
    protected String brojPasosa;

    /**
     * Gets the value of the tipDrzavljanstva property.
     * 
     * @return
     *     possible object is
     *     {@link TTipDrzavljanstva }
     *     
     */
    public TTipDrzavljanstva getTipDrzavljanstva() {
        return tipDrzavljanstva;
    }

    /**
     * Sets the value of the tipDrzavljanstva property.
     * 
     * @param value
     *     allowed object is
     *     {@link TTipDrzavljanstva }
     *     
     */
    public void setTipDrzavljanstva(TTipDrzavljanstva value) {
        this.tipDrzavljanstva = value;
    }

    /**
     * Gets the value of the jmbg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJmbg() {
        return jmbg;
    }

    /**
     * Sets the value of the jmbg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJmbg(String value) {
        this.jmbg = value;
    }

    /**
     * Gets the value of the brojPasosa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrojPasosa() {
        return brojPasosa;
    }

    /**
     * Sets the value of the brojPasosa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrojPasosa(String value) {
        this.brojPasosa = value;
    }

}
