//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.10 at 05:55:13 PM CET 
//


package rs.tim14.xml.model.korisnici;

import javax.xml.bind.annotation.*;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "ime",
        "prezime"
})
@XmlRootElement(name = "puno_ime")
public class PunoIme {

    @XmlElement(required = true)
    protected PunoIme.Ime ime;
    @XmlElement(required = true)
    protected PunoIme.Prezime prezime;
    public PunoIme.Ime getIme() {
        return ime;
    }

    public void setIme(PunoIme.Ime value) {
        this.ime = value;
    }

    public PunoIme.Prezime getPrezime() {
        return prezime;
    }
    public void setPrezime(PunoIme.Prezime value) {
        this.prezime = value;
    }
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "value"
    })
    public static class Ime {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "property")
        @XmlSchemaType(name = "anySimpleType")
        protected String property;
        @XmlAttribute(name = "datatype")
        @XmlSchemaType(name = "anySimpleType")
        protected String datatype;
        public String getValue() {
            return value;
        }

        public void setValue(String value) {
            this.value = value;
        }

        public String getProperty() {
            return property;
        }
        public void setProperty(String value) {
            this.property = value;
        }

        public String getDatatype() {
            return datatype;
        }

        public void setDatatype(String value) {
            this.datatype = value;
        }

    }
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "value"
    })
    public static class Prezime {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "property")
        @XmlSchemaType(name = "anySimpleType")
        protected String property;
        @XmlAttribute(name = "datatype")
        @XmlSchemaType(name = "anySimpleType")
        protected String datatype;
        public String getValue() {
            return value;
        }

        public void setValue(String value) {
            this.value = value;
        }

        public String getProperty() {
            return property;
        }

        public void setProperty(String value) {
            this.property = value;
        }

        public String getDatatype() {
            return datatype;
        }
        public void setDatatype(String value) {
            this.datatype = value;
        }

    }

    @Override
    public String toString() {
        final StringBuffer sb = new StringBuffer("{");
        sb.append("ime: '").append(ime).append('\'');
        sb.append(", prezime: '").append(prezime).append('\'').append("}");
        return sb.toString();
    }
}
