//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.10 at 05:55:13 PM CET 
//


package rs.tim14.xml.model.korisnici;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TFizicko_Lice complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TFizicko_Lice">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.xml.tim14.rs/korisnici}TLice">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.xml.tim14.rs/korisnici}puno_ime"/>
 *         &lt;element ref="{http://www.xml.tim14.rs/korisnici}drzavljanstvo" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TFizicko_Lice", propOrder = {
    "punoIme",
    "drzavljanstvo"
})
public class TFizickoLice
    extends TLice
{

    @XmlElement(name = "puno_ime", required = true)
    protected PunoIme punoIme;
    protected Drzavljanstvo drzavljanstvo;

    /**
     * Gets the value of the punoIme property.
     * 
     * @return
     *     possible object is
     *     {@link PunoIme }
     *     
     */
    public PunoIme getPunoIme() {
        return punoIme;
    }

    /**
     * Sets the value of the punoIme property.
     * 
     * @param value
     *     allowed object is
     *     {@link PunoIme }
     *     
     */
    public void setPunoIme(PunoIme value) {
        this.punoIme = value;
    }

    /**
     * Gets the value of the drzavljanstvo property.
     * 
     * @return
     *     possible object is
     *     {@link Drzavljanstvo }
     *     
     */
    public Drzavljanstvo getDrzavljanstvo() {
        return drzavljanstvo;
    }

    /**
     * Sets the value of the drzavljanstvo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Drzavljanstvo }
     *     
     */
    public void setDrzavljanstvo(Drzavljanstvo value) {
        this.drzavljanstvo = value;
    }

    @Override
    public String toString() {
        return "TFizickoLice{" +
            "punoIme=" + punoIme +
            ", drzavljanstvo=" + drzavljanstvo +
            ", adresa=" + adresa +
            ", brojMobilnogTelefona=" + brojMobilnogTelefona +
            ", brojFaksa=" + brojFaksa +
            ", email=" + email +
            '}';
    }
}
