//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.10 at 05:55:13 PM CET 
//


package rs.tim14.xml.model.korisnici;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TLice", propOrder = {
    "adresa",
    "brojMobilnogTelefona",
    "brojFaksa",
    "email"
})
@XmlSeeAlso({
    TFizickoLice.class,
    TPravnoLice.class
})
public abstract class TLice {

    @XmlElement(nillable = true)
    protected Adresa adresa;
    @XmlElementRef(name = "broj_mobilnog_telefona", namespace = "http://www.xml.tim14.rs/korisnici", type = JAXBElement.class, required = false)
    protected JAXBElement<String> brojMobilnogTelefona;
    @XmlElementRef(name = "broj_faksa", namespace = "http://www.xml.tim14.rs/korisnici", type = JAXBElement.class, required = false)
    protected JAXBElement<String> brojFaksa;
    @XmlElementRef(name = "email", namespace = "http://www.xml.tim14.rs/korisnici", type = JAXBElement.class, required = false)
    protected JAXBElement<String> email;
    public Adresa getAdresa() {
        return adresa;
    }
    public void setAdresa(Adresa value) {
        this.adresa = value;
    }
    public JAXBElement<String> getBrojMobilnogTelefona() {
        return brojMobilnogTelefona;
    }
    public void setBrojMobilnogTelefona(JAXBElement<String> value) {
        this.brojMobilnogTelefona = value;
    }
    public JAXBElement<String> getBrojFaksa() {
        return brojFaksa;
    }
    public void setBrojFaksa(JAXBElement<String> value) {
        this.brojFaksa = value;
    }
    public JAXBElement<String> getEmail() {
        return email;
    }
    public void setEmail(JAXBElement<String> value) {
        this.email = value;
    }

    public String toString(String prefix) {
        final StringBuffer sb = new StringBuffer();
        if (adresa != null) sb.append("\n").append(prefix).append("Adresa: ").append(adresa);
        if (brojMobilnogTelefona != null) sb.append("\n").append(prefix).append("Broj mobilnog telefona: ").append(brojMobilnogTelefona.getValue());
        if (brojFaksa != null) sb.append("\n").append(prefix).append("Broj faksa: ").append(brojFaksa.getValue());
        if (email != null) sb.append("\n").append(prefix).append("Email: ").append(email.getValue());
        return sb.toString();
    }
}
