//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.10 at 05:55:13 PM CET 
//


package rs.tim14.xml.model.korisnici;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TPravno_Lice", propOrder = {
    "poslovnoIme"
})
public class TPravnoLice
    extends TLice
{

    @XmlElement(name = "poslovno_ime", required = true)
    protected String poslovnoIme;
    public String getPoslovnoIme() {
        return poslovnoIme;
    }
    public void setPoslovnoIme(String value) {
        this.poslovnoIme = value;
    }

    public String toString(String prefix) {
        final StringBuffer sb = new StringBuffer();
        sb.append("\n").append(prefix).append("Poslovno ime: '").append(poslovnoIme).append('\'');
        sb.append(super.toString(prefix));
        return sb.toString();
    }
}
