//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.11 at 12:57:05 AM CET 
//


package rs.tim14.xml.model.zahtev_za_priznanje_ziga;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TVrsta_ziga.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TVrsta_ziga">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="INDUVIDUALNI"/>
 *     &lt;enumeration value="KOLEKTIVNI"/>
 *     &lt;enumeration value="ZIG_GARANCIJE"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TVrsta_ziga")
@XmlEnum
public enum TVrstaZiga {

    INDUVIDUALNI,
    KOLEKTIVNI,
    ZIG_GARANCIJE;

    public String value() {
        return name();
    }

    public static TVrstaZiga fromValue(String v) {
        return valueOf(v);
    }

}
