//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.11 at 12:57:05 AM CET 
//


package rs.tim14.xml.model.zahtev_za_priznanje_ziga;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TVrsta_znaka.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TVrsta_znaka">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="VERBALNI"/>
 *     &lt;enumeration value="GRAFICKI"/>
 *     &lt;enumeration value="KOMBINOVANI"/>
 *     &lt;enumeration value="TRODIMENZIONALNI"/>
 *     &lt;enumeration value="DRUGI"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TVrsta_znaka")
@XmlEnum
public enum TVrstaZnaka {

    VERBALNI,
    GRAFICKI,
    KOMBINOVANI,
    TRODIMENZIONALNI,
    DRUGI;

    public String value() {
        return name();
    }

    public static TVrstaZnaka fromValue(String v) {
        return valueOf(v);
    }

}
