//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.10 at 05:55:13 PM CET 
//


package rs.tim14.xml.model.zahtev_za_priznanje_patenta;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rs.tim14.xml.zahtev_za_priznanje_patenta package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ZahtevZaPriznanjePatentaOsnovnaPrijava_QNAME = new QName("http://www.xml.tim14.rs/zahtev_za_priznanje_patenta", "osnovna_prijava");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rs.tim14.xml.zahtev_za_priznanje_patenta
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ZahtevZaPriznanjePatenta }
     * 
     */
    public ZahtevZaPriznanjePatenta createZahtevZaPriznanjePatenta() {
        return new ZahtevZaPriznanjePatenta();
    }

    /**
     * Create an instance of {@link TPrijava }
     * 
     */
    public TPrijava createTPrijava() {
        return new TPrijava();
    }

    /**
     * Create an instance of {@link ZahtevZaPriznanjePatenta.Pronalazak }
     * 
     */
    public ZahtevZaPriznanjePatenta.Pronalazak createZahtevZaPriznanjePatentaPronalazak() {
        return new ZahtevZaPriznanjePatenta.Pronalazak();
    }

    /**
     * Create an instance of {@link ZahtevZaPriznanjePatenta.PodaciOPodnosiocu }
     * 
     */
    public ZahtevZaPriznanjePatenta.PodaciOPodnosiocu createZahtevZaPriznanjePatentaPodaciOPodnosiocu() {
        return new ZahtevZaPriznanjePatenta.PodaciOPodnosiocu();
    }

    /**
     * Create an instance of {@link ZahtevZaPriznanjePatenta.PodaciOPronalazacu }
     * 
     */
    public ZahtevZaPriznanjePatenta.PodaciOPronalazacu createZahtevZaPriznanjePatentaPodaciOPronalazacu() {
        return new ZahtevZaPriznanjePatenta.PodaciOPronalazacu();
    }

    /**
     * Create an instance of {@link ZahtevZaPriznanjePatenta.PodaciOPunomocniku }
     * 
     */
    public ZahtevZaPriznanjePatenta.PodaciOPunomocniku createZahtevZaPriznanjePatentaPodaciOPunomocniku() {
        return new ZahtevZaPriznanjePatenta.PodaciOPunomocniku();
    }

    /**
     * Create an instance of {@link ZahtevZaPriznanjePatenta.PodaciODostavljanju }
     * 
     */
    public ZahtevZaPriznanjePatenta.PodaciODostavljanju createZahtevZaPriznanjePatentaPodaciODostavljanju() {
        return new ZahtevZaPriznanjePatenta.PodaciODostavljanju();
    }

    /**
     * Create an instance of {@link ZahtevZaPriznanjePatenta.ZahtevZaPriznanjePravaPrvenstvaIzRanijihPrijava }
     * 
     */
    public ZahtevZaPriznanjePatenta.ZahtevZaPriznanjePravaPrvenstvaIzRanijihPrijava createZahtevZaPriznanjePatentaZahtevZaPriznanjePravaPrvenstvaIzRanijihPrijava() {
        return new ZahtevZaPriznanjePatenta.ZahtevZaPriznanjePravaPrvenstvaIzRanijihPrijava();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TPrijava }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.xml.tim14.rs/zahtev_za_priznanje_patenta", name = "osnovna_prijava", scope = ZahtevZaPriznanjePatenta.class)
    public JAXBElement<TPrijava> createZahtevZaPriznanjePatentaOsnovnaPrijava(TPrijava value) {
        return new JAXBElement<TPrijava>(_ZahtevZaPriznanjePatentaOsnovnaPrijava_QNAME, TPrijava.class, ZahtevZaPriznanjePatenta.class, value);
    }

}
