//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.10 at 05:55:13 PM CET 
//


package rs.tim14.xml.model.zahtev_za_priznanje_patenta;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TNacin_dostavljanja.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TNacin_dostavljanja">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="u_papirnoj_formi"/>
 *     &lt;enumeration value="elektronskim_putem"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TNacin_dostavljanja")
@XmlEnum
public enum TNacinDostavljanja {

    @XmlEnumValue("u_papirnoj_formi")
    U_PAPIRNOJ_FORMI("u_papirnoj_formi"),
    @XmlEnumValue("elektronskim_putem")
    ELEKTRONSKIM_PUTEM("elektronskim_putem");
    private final String value;

    TNacinDostavljanja(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TNacinDostavljanja fromValue(String v) {
        for (TNacinDostavljanja c: TNacinDostavljanja.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
