//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.10 at 05:55:13 PM CET 
//


package rs.tim14.xml.model.zahtev_za_priznanje_patenta;

import java.math.BigInteger;
import java.util.Date;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TPrijava", propOrder = {
    "brojPrijave",
    "datumPodnosenja",
    "datumPrijema",
    "oznakaDrzave"
})
public class TPrijava {

    @XmlElement(name = "broj_prijave", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger brojPrijave;
    @XmlElement(name = "datum_podnosenja", required = true)
    @XmlSchemaType(name = "date")
    protected Date datumPodnosenja;
    @XmlElement(name = "datum_prijema")
    @XmlSchemaType(name = "date")
    protected Date datumPrijema;
    @XmlElement(name = "oznaka_drzave")
    protected String oznakaDrzave;

    public BigInteger getBrojPrijave() {
        return brojPrijave;
    }

    public void setBrojPrijave(BigInteger value) {
        this.brojPrijave = value;
    }

    public Date getDatumPodnosenja() {
        return datumPodnosenja;
    }

    public void setDatumPodnosenja(Date value) {
        this.datumPodnosenja = value;
    }

    public Date getDatumPrijema() {
        return datumPrijema;
    }

    public void setDatumPrijema(Date value) {
        this.datumPrijema = value;
    }

    public String getOznakaDrzave() {
        return oznakaDrzave;
    }

    public void setOznakaDrzave(String value) {
        this.oznakaDrzave = value;
    }

    @Override
    public String toString() {
        final StringBuffer sb = new StringBuffer("{");
        sb.append("broj prijave: ").append(brojPrijave);
        if (datumPodnosenja != null) sb.append(", datum podnosenja: ").append(datumPodnosenja);
        if (datumPrijema != null) sb.append(", datum prijema: ").append(datumPrijema);
        if (oznakaDrzave != null) sb.append(", oznaka drzave:'").append(oznakaDrzave).append('\'');
        sb.append('}');
        return sb.toString();
    }
}
