//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.10 at 05:55:13 PM CET 
//


package rs.tim14.xml.model.zahtev_za_priznanje_patenta;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import rs.tim14.xml.model.korisnici.Adresa;
import rs.tim14.xml.model.korisnici.TFizickoLice;
import rs.tim14.xml.model.korisnici.TLice;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "prijava",
    "pronalazak",
    "podaciOPodnosiocu",
    "podaciOPronalazacu",
    "podaciOPunomocniku",
    "podaciODostavljanju",
    "osnovnaPrijava",
    "zahtevZaPriznanjePravaPrvenstvaIzRanijihPrijava"
})
@XmlRootElement(name = "zahtev_za_priznanje_patenta")
public class ZahtevZaPriznanjePatenta {

    @XmlElement(required = true)
    protected TPrijava prijava;
    @XmlElement(required = true)
    protected Pronalazak pronalazak;
    @XmlElement(name = "podaci_o_podnosiocu", required = true)
    protected PodaciOPodnosiocu podaciOPodnosiocu;
    @XmlElement(name = "podaci_o_pronalazacu", required = true)
    protected PodaciOPronalazacu podaciOPronalazacu;
    @XmlElement(name = "podaci_o_punomocniku", required = true)
    protected PodaciOPunomocniku podaciOPunomocniku;
    @XmlElement(name = "podaci_o_dostavljanju", required = true)
    protected PodaciODostavljanju podaciODostavljanju;
    @XmlElement(name = "osnovna_prijava", required = false)
    protected TPrijava osnovnaPrijava;
    @XmlElement(name = "zahtev_za_priznanje_prava_prvenstva_iz_ranijih_prijava", required = true)
    protected ZahtevZaPriznanjePravaPrvenstvaIzRanijihPrijava zahtevZaPriznanjePravaPrvenstvaIzRanijihPrijava;

    public TPrijava getPrijava() {
        return prijava;
    }
    public void setPrijava(TPrijava value) {
        this.prijava = value;
    }
    public Pronalazak getPronalazak() {
        return pronalazak;
    }
    public void setPronalazak(Pronalazak value) {
        this.pronalazak = value;
    }
    public PodaciOPodnosiocu getPodaciOPodnosiocu() {
        return podaciOPodnosiocu;
    }
    public void setPodaciOPodnosiocu(PodaciOPodnosiocu value) {
        this.podaciOPodnosiocu = value;
    }
    public PodaciOPronalazacu getPodaciOPronalazacu() {
        return podaciOPronalazacu;
    }
    public void setPodaciOPronalazacu(PodaciOPronalazacu value) {
        this.podaciOPronalazacu = value;
    }
    public PodaciOPunomocniku getPodaciOPunomocniku() {
        return podaciOPunomocniku;
    }
    public void setPodaciOPunomocniku(PodaciOPunomocniku value) {
        this.podaciOPunomocniku = value;
    }
    public PodaciODostavljanju getPodaciODostavljanju() {
        return podaciODostavljanju;
    }
    public void setPodaciODostavljanju(PodaciODostavljanju value) {
        this.podaciODostavljanju = value;
    }
    public TPrijava getOsnovnaPrijava() {
        return osnovnaPrijava;
    }
    public void setOsnovnaPrijava(TPrijava value) {
        this.osnovnaPrijava = value;
    }
    public ZahtevZaPriznanjePravaPrvenstvaIzRanijihPrijava getZahtevZaPriznanjePravaPrvenstvaIzRanijihPrijava() {
        return zahtevZaPriznanjePravaPrvenstvaIzRanijihPrijava;
    }
    public void setZahtevZaPriznanjePravaPrvenstvaIzRanijihPrijava(ZahtevZaPriznanjePravaPrvenstvaIzRanijihPrijava value) {
        this.zahtevZaPriznanjePravaPrvenstvaIzRanijihPrijava = value;
    }

    @Override
    public String toString() {
        final StringBuffer sb = new StringBuffer("ZahtevZaPriznanjePatenta: ");
        sb.append("\n\tPrijava: ").append(prijava);
        sb.append("\n\tPronalazak: ").append(pronalazak);
        sb.append("\n\tPodaci o podnosiocu: ").append(podaciOPodnosiocu);
        sb.append("\n\tPodaci o pronalazacu: ").append(podaciOPronalazacu);
        sb.append("\n\tPodaci o punomocniku: ").append(podaciOPunomocniku);
        sb.append("\n\tPodaci o dostavljanju: ").append(podaciODostavljanju);
        sb.append("\n\tOsnovna prijava: ").append(osnovnaPrijava);
        sb.append("\n\tZahtev za priznanje prava prvenstva iz ranijih prijava:").append(zahtevZaPriznanjePravaPrvenstvaIzRanijihPrijava);
        sb.append('}');
        return sb.toString();
    }
}
