//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.11 at 12:43:21 PM CET 
//


package rs.tim14.xml.model.zahtev_za_priznanje_ziga;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rs.tim14.xml.zahtev_za_priznanje_ziga package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 *
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ZahtevZaPriznanjeZigaZnakVrstaZnakaDrugaVrstaZnaka_QNAME = new QName("http://www.xml.tim14.rs/zahtev_za_priznanje_ziga", "druga_vrsta_znaka");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rs.tim14.xml.zahtev_za_priznanje_ziga
     *
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ZahtevZaPriznanjeZiga }
     *
     */
    public ZahtevZaPriznanjeZiga createZahtevZaPriznanjeZiga() {
        return new ZahtevZaPriznanjeZiga();
    }

    /**
     * Create an instance of {@link Znak }
     *
     */
    public Znak createZahtevZaPriznanjeZigaZnak() {
        return new Znak();
    }

    /**
     * Create an instance of {@link PravoPrvenstva }
     *
     */
    public PravoPrvenstva createZahtevZaPriznanjeZigaPravoPrvenstva() {
        return new PravoPrvenstva();
    }

    /**
     * Create an instance of {@link Takse }
     *
     */
    public Takse createZahtevZaPriznanjeZigaTakse() {
        return new Takse();
    }

    /**
     * Create an instance of {@link PriloziUzZahtev }
     *
     */
    public PriloziUzZahtev createZahtevZaPriznanjeZigaPriloziUzZahtev() {
        return new PriloziUzZahtev();
    }

    /**
     * Create an instance of {@link VrstaZnaka }
     *
     */
    public VrstaZnaka createZahtevZaPriznanjeZigaZnakVrstaZnaka() {
        return new VrstaZnaka();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "http://www.xml.tim14.rs/zahtev_za_priznanje_ziga", name = "druga_vrsta_znaka", scope = VrstaZnaka.class)
    public JAXBElement<String> createZahtevZaPriznanjeZigaZnakVrstaZnakaDrugaVrstaZnaka(String value) {
        return new JAXBElement<String>(_ZahtevZaPriznanjeZigaZnakVrstaZnakaDrugaVrstaZnaka_QNAME, String.class, VrstaZnaka.class, value);
    }

    public ResenjeZahteva createResenjeZahteva() {
        return new ResenjeZahteva();
    }


}
